# Generated by Django 5.1 on 2024-08-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='Default Value', max_length=100)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('integer_field', models.IntegerField(default=0)),
                ('float_field', models.FloatField(default=0.0)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_field', models.DateField(auto_now_add=True)),
                ('datetime_field', models.DateTimeField(auto_now=True)),
                ('boolean_field', models.BooleanField(default=True)),
                ('null_boolean_field', models.BooleanField(blank=True, null=True)),
                ('email_field', models.EmailField(max_length=254, unique=True)),
                ('url_field', models.URLField(blank=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('choice_field', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B'), ('C', 'Choice C')], default='A', max_length=2)),
                ('slug_field', models.SlugField(blank=True, null=True, unique=True)),
                ('foreign_key_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_foreign_key', to='app.comprehensivemodel')),
                ('many_to_many_field', models.ManyToManyField(blank=True, to='app.comprehensivemodel')),
                ('one_to_one_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_one_to_one', to='app.comprehensivemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
