# Generated by Django 5.1 on 2024-08-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comprehensivemodel_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprehensivemodel',
            name='choice_field',
        ),
        migrations.RemoveField(
            model_name='comprehensivemodel',
            name='foreign_key_field',
        ),
        migrations.RemoveField(
            model_name='comprehensivemodel',
            name='many_to_many_field',
        ),
        migrations.RemoveField(
            model_name='comprehensivemodel',
            name='one_to_one_field',
        ),
        migrations.RemoveField(
            model_name='comprehensivemodel',
            name='slug_field',
        ),
    ]
