# Generated by Django 5.1 on 2024-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_author_book_delete_comprehensivemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='bio',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
